require('dotenv').config(); // Baris ini harus ada paling atas untuk memuat .env secara lokal

const fs = require('fs');
const path = require('path');

// Pastikan folder target ada, jalur ini relatif terhadap lokasi generate_config.js
const targetDir = './admin/js'; // <-- JALUR DISESUAIKAN
if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
}

const configContent = `
// This file is auto-generated during Netlify build or local generation.
// Do not edit this file directly.

window.STORAPEDIA_API_KEY = "${process.env.VITE_STORAPEDIA_API_KEY || 'YOUR_LOCAL_FALLBACK_API_KEY'}";
window.STORAPEDIA_AUTH_DOMAIN = "${process.env.VITE_STORAPEDIA_AUTH_DOMAIN || 'YOUR_LOCAL_FALLBACK_AUTH_DOMAIN'}";
window.STORAPEDIA_PROJECT_ID = "${process.env.VITE_STORAPEDIA_PROJECT_ID || 'YOUR_LOCAL_FALLBACK_PROJECT_ID'}";
window.STORAPEDIA_STORAGE_BUCKET = "${process.env.VITE_STORAPEDIA_STORAGE_BUCKET || 'YOUR_LOCAL_FALLBACK_STORAGE_BUCKET'}";
window.STORAPEDIA_MESSAGING_SENDER_ID = "${process.env.VITE_STORAPEDIA_MESSAGING_SENDER_ID || 'YOUR_LOCAL_FALLBACK_MESSAGING_SENDER_ID'}";
window.STORAPEDIA_APP_ID = "${process.env.VITE_STORAPEDIA_APP_ID || 'YOUR_LOCAL_FALLBACK_APP_ID'}";
window.STORAPEDIA_DATABASE_URL = "${process.env.VITE_STORAPEDIA_DATABASE_URL || 'YOUR_LOCAL_FALLBACK_DATABASE_URL'}";
window.Maps_API_KEY = "${process.env.VITE_MAPS_API_KEY || 'YOUR_LOCAL_FALLBACK_MAPS_API_KEY'}";
`;

// Tulis konten ke file config.js
const outputPath = path.join(targetDir, 'config.js');
fs.writeFileSync(outputPath, configContent);
console.log(`Generated ${outputPath} with environment variables.`);