
// This file is auto-generated during Netlify build or local generation.
// Do not edit this file directly.

window.STORAPEDIA_API_KEY = "AIzaSyBeX6K3ejM-zu755LVDDMwgxBi-KW-ogx4_LOCAL_DEV";
window.STORAPEDIA_AUTH_DOMAIN = "storapedia-dev.firebaseapp.com";
window.STORAPEDIA_PROJECT_ID = "storapedia-dev";
window.STORAPEDIA_STORAGE_BUCKET = "storapedia-dev.appspot.com";
window.STORAPEDIA_MESSAGING_SENDER_ID = "145464021088_DEV";
window.STORAPEDIA_APP_ID = "1:145464021088:web:1e24a2847994ac5003f305_DEV";
window.STORAPEDIA_DATABASE_URL = "https://storapedia-dev-rtdb.firebaseio.com/";
window.Maps_API_KEY = ""AIzaSyADCv-AX09lIYq6Gr7Gm56rChp4kS0J08Q_LOCAL_DEV";
